
#ifndef _SIMILLIMUM_AUTO_VERSION_INFORMATION_H_
#define _SIMILLIMUM_AUTO_VERSION_INFORMATION_H_

#define SM_BUILD_TAG		"dev"
#define SM_BUILD_REV		"3921"
#define SM_BUILD_CSET		"96e96debb70d"
#define SM_BUILD_MAJOR		"1"
#define SM_BUILD_MINOR		"6"
#define SM_BUILD_RELEASE	"0"

#define SM_BUILD_UNIQUEID SM_BUILD_REV ":" SM_BUILD_CSET

#define SM_VERSION_STRING	"1.6.0-dev+3921"
#define SM_VERSION_FILE		1,6,0,0

#endif /* _SIMILLIMUM_AUTO_VERSION_INFORMATION_H_ */

